---
title: "Dashboard WORLD"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(flexdashboard)
library(tidyverse)

```



```{r}

source(file="C:/Users/Jl/Desktop/TP/code_Dash1.R")

```
# Analyse du monde

### Evolution total de la population  dans le monde 

```{r}

ggplot(filter(wpp2019_pop, Region_Subregion_Country_area == "WORLD") ) + 
  aes(x = annee, y = population, group = 1, color = population) +
  geom_point() +
  geom_line()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1) ) +
  scale_x_continuous( breaks= seq(1950,2020,10)  )

```


-----------------------------------------------------------------------

### Evolution total de la production alimentaire dans le monde 

```{r}

ggplot(filter(food) ) + 
  aes(x = annee, y = food, color = Item) +
  geom_line(aes(group= Item)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1) )+
  scale_x_discrete( breaks= seq(1950,2020,5)  )

```

### Energie renouvelable

```{r}
ggplot(energy_renouvelable) +
  aes(x = year, y = consommation, color=genre_energy)+
    geom_area(aes(fill= genre_energy))
  
```


### Combustible

```{r}
# ======= GRAPHIQUE des combustibles
ggplot(energy_combustible) +
  aes(x = year, y = consommation, color=genre_energy)+
  geom_area(aes(fill= genre_energy)) 

```